### ISSUE TITLE
再生ボタンの表示

### ISSUE THREAD

**Issue by Kousuke-N** [cyder-akashi/AktivaTurbo#3]
再生ボタンの表示

* 中央に三角形のボタンを表示
* 押すと一時停止のアイコンに
* もう一度押すと三角形のアイコンに

**Comment by Mori-Atsushi** [comment]
再生ボタンの表示

* 中央に三角形のボタンを表示
* 押すと一時停止のアイコンに
* もう一度押すと三角形のアイコンに
